### ISSUE TITLE
Duplicate this repo to e.g. wheredoesmymoneygo-template

### ISSUE THREAD

**Issue by rufuspollock** [openspending/wheredoesmymoneygo.org#10]
This repo should just be for wheredoesmymoneygo.org and we should have a duplicate repo which acts as the template for making "satellite" sites ...

**Comment by smagch** [comment]
It seems that you created a repo [openspending/satellite-template](https://github.com/openspending/satellite-template/). Since abstract template is hosted on [openspending/satellite-template](https://github.com/openspending/satellite-template/) now, what this repo is going to be? Do you host real source files of http://wheredoesmymoneygo.org/ here?

**Comment by rufuspollock** [comment]
@smagch yes, exactly. This is source for wheredoesmymoneygo.org which may have tweaks and customizations re the template.

**Comment by rufuspollock** [comment]
Closing this issue as the copying has happened.
